version: '3'
services:
  shop_api:
    build:
      context: .
    command: sh -c "python3 manage.py runserver 0.0.0.0:8000"
    ports:
      -'8001:8000' #host:container
    depends_on:
      - shop_data
  shop_data:
    image: "postgres:14"
    environment:
      POSTGRES_DB: 'shop_api_database'
      POSTGRES_USER: 'shop_api_database_user'
      POSTGRES_PASSWORD: '1234'
    volumes:
      - 'shop-data:/var/lib/postgresql/data'
volumes:
  shop-data: